// <auto-generated />
using System;
using GotsThorlabs.Database.EntityRepo;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GotsThorlabs.Migrations
{
    [DbContext(typeof(ThorlabsDbContext))]
    [Migration("20260726190000_AddCameraSettingsJson")]
    partial class AddCameraSettingsJson
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.36");

            modelBuilder.Entity("GotsThorlabs.Database.EntityRepo.Entities.Camera", b =>
            {
                b.Property<string>("CameraId")
                    .HasColumnType("TEXT")
                    .HasColumnName("cameraId");

                b.Property<string>("DriverType")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("driverType");

                b.Property<string>("Features")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("features");

                b.Property<string>("LocalIdentifier")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("localIdentifier");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("TEXT")
                    .HasColumnName("name");

                b.Property<string>("SettingsJson")
                    .HasColumnType("TEXT")
                    .HasColumnName("settingsJson");

                b.HasKey("CameraId");

                b.ToTable("camera", (string)null);
            });
#pragma warning restore 612, 618
        }
    }
}
