// <auto-generated />
using System;
using GotsThorlabs.Database.EntityRepo;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GotsThorlabs.Migrations
{
    [DbContext(typeof(ThorlabsDbContext))]
    [Migration("20260807172659_AddMotorStepCalibration")]
    partial class AddMotorStepCalibration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.36");

            modelBuilder.Entity("GotsThorlabs.Database.EntityRepo.Entities.AxisStepCalibration", b =>
                {
                    b.Property<string>("AxisStepCalibrationId")
                        .HasColumnType("TEXT")
                        .HasColumnName("axisStepCalibrationId");

                    b.Property<string>("AxisName")
                        .IsRequired()
                        .HasColumnType("TEXT(5)")
                        .HasColumnName("axisName");

                    b.Property<string>("HysteresisPct")
                        .HasColumnType("TEXT")
                        .HasColumnName("hysteresisPct");

                    b.Property<string>("MotorCalibrationId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("motorCalibrationId");

                    b.Property<string>("RelativeErrorPct")
                        .HasColumnType("TEXT")
                        .HasColumnName("relativeErrorPct");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("StepSizeNm")
                        .HasColumnType("TEXT")
                        .HasColumnName("stepSizeNm");

                    b.Property<string>("StepSizeNmBackward")
                        .HasColumnType("TEXT")
                        .HasColumnName("stepSizeNmBackward");

                    b.Property<string>("StepSizeNmForward")
                        .HasColumnType("TEXT")
                        .HasColumnName("stepSizeNmForward");

                    b.HasKey("AxisStepCalibrationId");

                    b.HasIndex(new[] { "MotorCalibrationId" }, "IX_axisStepCalibration_motorCalibrationId");

                    b.ToTable("axisStepCalibration", (string)null);
                });

            modelBuilder.Entity("GotsThorlabs.Database.EntityRepo.Entities.AxisStepMeasurement", b =>
                {
                    b.Property<string>("AxisStepMeasurementId")
                        .HasColumnType("TEXT")
                        .HasColumnName("axisStepMeasurementId");

                    b.Property<string>("AxisStepCalibrationId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("axisStepCalibrationId");

                    b.Property<string>("CaliperReadingMm")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("caliperReadingMm");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("TEXT(10)")
                        .HasColumnName("direction");

                    b.Property<string>("MeasuredAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("measuredAt");

                    b.Property<long>("Sequence")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sequence");

                    b.Property<long>("StepsCommanded")
                        .HasColumnType("INTEGER")
                        .HasColumnName("stepsCommanded");

                    b.HasKey("AxisStepMeasurementId");

                    b.HasIndex(new[] { "AxisStepCalibrationId" }, "IX_axisStepMeasurement_axisStepCalibrationId");

                    b.ToTable("axisStepMeasurement", (string)null);
                });

            modelBuilder.Entity("GotsThorlabs.Database.EntityRepo.Entities.Camera", b =>
                {
                    b.Property<string>("CameraId")
                        .HasColumnType("TEXT")
                        .HasColumnName("cameraId");

                    b.Property<string>("DriverType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("driverType")
                        .HasDefaultValueSql("'generic'");

                    b.Property<string>("Features")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("features");

                    b.Property<string>("LocalIdentifier")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("localIdentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("SettingsJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("settingsJson");

                    b.HasKey("CameraId");

                    b.ToTable("camera", (string)null);
                });

            modelBuilder.Entity("GotsThorlabs.Database.EntityRepo.Entities.GroupCalibration", b =>
                {
                    b.Property<string>("GroupCailbrationId")
                        .HasColumnType("TEXT")
                        .HasColumnName("groupCailbrationId");

                    b.Property<string>("AditionalInfo")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("aditionalInfo");

                    b.Property<string>("CameraId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("cameraId");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("date");

                    b.Property<string>("IncreaseId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("increaseId");

                    b.Property<string>("MicroscopeId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("microscopeId");

                    b.HasKey("GroupCailbrationId");

                    b.HasIndex(new[] { "CameraId" }, "IX_groupCalibration_cameraId");

                    b.HasIndex(new[] { "IncreaseId" }, "IX_groupCalibration_increaseId");

                    b.HasIndex(new[] { "MicroscopeId" }, "IX_groupCalibration_microscopeId");

                    b.ToTable("groupCalibration", (string)null);
                });

            modelBuilder.Entity("GotsThorlabs.Database.EntityRepo.Entities.Image", b =>
                {
                    b.Property<long>("IdImage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("idImage");

                    b.Property<double?>("GausianVal")
                        .HasColumnType("REAL")
                        .HasColumnName("gausianVal");

                    b.Property<long>("IdTour")
                        .HasColumnType("INTEGER")
                        .HasColumnName("idTour");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("path");

                    b.Property<long>("X")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Y")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Z")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdImage");

                    b.HasIndex(new[] { "IdTour" }, "IX_image_idTour");

                    b.ToTable("image", (string)null);
                });

            modelBuilder.Entity("GotsThorlabs.Database.EntityRepo.Entities.Increase", b =>
                {
                    b.Property<string>("IncreaseId")
                        .HasColumnType("TEXT")
                        .HasColumnName("increaseId");

                    b.Property<string>("AditionalInfo")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("aditionalInfo");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("IncreaseId");

                    b.ToTable("increase", (string)null);
                });

            modelBuilder.Entity("GotsThorlabs.Database.EntityRepo.Entities.Microscope", b =>
                {
                    b.Property<string>("MicroscopeId")
                        .HasColumnType("TEXT")
                        .HasColumnName("microscopeId");

                    b.Property<string>("AditionalInfo")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("aditionalInfo");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("brand");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Site")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("site");

                    b.HasKey("MicroscopeId");

                    b.ToTable("microscope", (string)null);
                });

            modelBuilder.Entity("GotsThorlabs.Database.EntityRepo.Entities.MotorCalibration", b =>
                {
                    b.Property<string>("MotorCalibrationId")
                        .HasColumnType("TEXT")
                        .HasColumnName("motorCalibrationId");

                    b.Property<long>("Acepted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("acepted");

                    b.Property<string>("AditionalInfo")
                        .HasColumnType("TEXT")
                        .HasColumnName("aditionalInfo");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("date");

                    b.Property<string>("GroupCailbrationId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("groupCailbrationId");

                    b.Property<string>("KimDeviceId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("kimDeviceId");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<long>("StepAcceleration")
                        .HasColumnType("INTEGER")
                        .HasColumnName("stepAcceleration");

                    b.Property<long>("StepRate")
                        .HasColumnType("INTEGER")
                        .HasColumnName("stepRate");

                    b.HasKey("MotorCalibrationId");

                    b.HasIndex(new[] { "GroupCailbrationId" }, "IX_motorCalibration_groupCailbrationId");

                    b.ToTable("motorCalibration", (string)null);
                });

            modelBuilder.Entity("GotsThorlabs.Database.EntityRepo.Entities.PicsCalibration", b =>
                {
                    b.Property<string>("PicsCalibrationId")
                        .HasColumnType("TEXT")
                        .HasColumnName("picsCalibrationId");

                    b.Property<long>("Acepted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("acepted");

                    b.Property<string>("AxeDirectionCalibration")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("axeDirectionCalibration");

                    b.Property<string>("AxisMovementName")
                        .HasColumnType("TEXT(5)")
                        .HasColumnName("axisMovementName");

                    b.Property<string>("Confidence")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("confidence");

                    b.Property<string>("Dx")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("dx");

                    b.Property<string>("Dy")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("dy");

                    b.Property<string>("GroupCailbrationId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("groupCailbrationId");

                    b.Property<string>("MeasureUnit")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("measureUnit");

                    b.Property<string>("MovementValue")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("movementValue");

                    b.Property<long?>("NumberOfSteps")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("numberOfSteps")
                        .HasDefaultValueSql("1");

                    b.Property<string>("Pic1")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("pic1");

                    b.Property<string>("Pic2")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("pic2");

                    b.HasKey("PicsCalibrationId");

                    b.HasIndex(new[] { "GroupCailbrationId" }, "IX_picsCalibration_groupCailbrationId");

                    b.ToTable("picsCalibration", (string)null);
                });

            modelBuilder.Entity("GotsThorlabs.Database.EntityRepo.Entities.Tour", b =>
                {
                    b.Property<long>("IdTour")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("idTour");

                    b.Property<long>("Camera")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("date");

                    b.Property<string>("EndStatus")
                        .HasColumnType("TEXT")
                        .HasColumnName("endStatus");

                    b.Property<string>("NameFolder")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nameFolder");

                    b.Property<long>("NumberX")
                        .HasColumnType("INTEGER");

                    b.Property<long>("NumberY")
                        .HasColumnType("INTEGER");

                    b.Property<long>("NumberZ")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PicsCalibrationId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdTour");

                    b.HasIndex("PicsCalibrationId");

                    b.ToTable("tour", (string)null);
                });

            modelBuilder.Entity("GotsThorlabs.Database.EntityRepo.Entities.User", b =>
                {
                    b.Property<long>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("idUser");

                    b.Property<string>("EMail")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("eMail");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nickname");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("password");

                    b.HasKey("IdUser");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("GotsThorlabs.Database.EntityRepo.Entities.AxisStepCalibration", b =>
                {
                    b.HasOne("GotsThorlabs.Database.EntityRepo.Entities.MotorCalibration", "MotorCalibration")
                        .WithMany("AxisStepCalibrations")
                        .HasForeignKey("MotorCalibrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MotorCalibration");
                });

            modelBuilder.Entity("GotsThorlabs.Database.EntityRepo.Entities.AxisStepMeasurement", b =>
                {
                    b.HasOne("GotsThorlabs.Database.EntityRepo.Entities.AxisStepCalibration", "AxisStepCalibration")
                        .WithMany("AxisStepMeasurements")
                        .HasForeignKey("AxisStepCalibrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AxisStepCalibration");
                });

            modelBuilder.Entity("GotsThorlabs.Database.EntityRepo.Entities.GroupCalibration", b =>
                {
                    b.HasOne("GotsThorlabs.Database.EntityRepo.Entities.Camera", "Camera")
                        .WithMany("GroupCalibrations")
                        .HasForeignKey("CameraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GotsThorlabs.Database.EntityRepo.Entities.Increase", "Increase")
                        .WithMany("GroupCalibrations")
                        .HasForeignKey("IncreaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GotsThorlabs.Database.EntityRepo.Entities.Microscope", "Microscope")
                        .WithMany("GroupCalibrations")
                        .HasForeignKey("MicroscopeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Camera");

                    b.Navigation("Increase");

                    b.Navigation("Microscope");
                });

            modelBuilder.Entity("GotsThorlabs.Database.EntityRepo.Entities.Image", b =>
                {
                    b.HasOne("GotsThorlabs.Database.EntityRepo.Entities.Tour", "IdTourNavigation")
                        .WithMany("Images")
                        .HasForeignKey("IdTour")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdTourNavigation");
                });

            modelBuilder.Entity("GotsThorlabs.Database.EntityRepo.Entities.MotorCalibration", b =>
                {
                    b.HasOne("GotsThorlabs.Database.EntityRepo.Entities.GroupCalibration", "GroupCailbration")
                        .WithMany("MotorCalibrations")
                        .HasForeignKey("GroupCailbrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GroupCailbration");
                });

            modelBuilder.Entity("GotsThorlabs.Database.EntityRepo.Entities.PicsCalibration", b =>
                {
                    b.HasOne("GotsThorlabs.Database.EntityRepo.Entities.GroupCalibration", "GroupCailbration")
                        .WithMany("PicsCalibrations")
                        .HasForeignKey("GroupCailbrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GroupCailbration");
                });

            modelBuilder.Entity("GotsThorlabs.Database.EntityRepo.Entities.Tour", b =>
                {
                    b.HasOne("GotsThorlabs.Database.EntityRepo.Entities.PicsCalibration", "PicsCalibration")
                        .WithMany("Tours")
                        .HasForeignKey("PicsCalibrationId")
                        .IsRequired();

                    b.Navigation("PicsCalibration");
                });

            modelBuilder.Entity("GotsThorlabs.Database.EntityRepo.Entities.AxisStepCalibration", b =>
                {
                    b.Navigation("AxisStepMeasurements");
                });

            modelBuilder.Entity("GotsThorlabs.Database.EntityRepo.Entities.Camera", b =>
                {
                    b.Navigation("GroupCalibrations");
                });

            modelBuilder.Entity("GotsThorlabs.Database.EntityRepo.Entities.GroupCalibration", b =>
                {
                    b.Navigation("MotorCalibrations");

                    b.Navigation("PicsCalibrations");
                });

            modelBuilder.Entity("GotsThorlabs.Database.EntityRepo.Entities.Increase", b =>
                {
                    b.Navigation("GroupCalibrations");
                });

            modelBuilder.Entity("GotsThorlabs.Database.EntityRepo.Entities.Microscope", b =>
                {
                    b.Navigation("GroupCalibrations");
                });

            modelBuilder.Entity("GotsThorlabs.Database.EntityRepo.Entities.MotorCalibration", b =>
                {
                    b.Navigation("AxisStepCalibrations");
                });

            modelBuilder.Entity("GotsThorlabs.Database.EntityRepo.Entities.PicsCalibration", b =>
                {
                    b.Navigation("Tours");
                });

            modelBuilder.Entity("GotsThorlabs.Database.EntityRepo.Entities.Tour", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
