// <auto-generated />
using System;
using GotsThorlabs.Database.EntityRepo;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GotsThorlabs.Migrations
{
    [DbContext(typeof(ThorlabsDbContext))]
    partial class ThorlabsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.36");

            modelBuilder.Entity("GotsThorlabs.Database.EntityRepo.Entities.Camera", b =>
                {
                    b.Property<Guid>("CameraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("cameraId");

                    b.Property<string>("Features")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT")
                        .HasColumnName("features");

                    b.Property<string>("LocalIdentifier")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT")
                        .HasColumnName("localIdentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("CameraId");

                    b.ToTable("camera", (string)null);
                });

            modelBuilder.Entity("GotsThorlabs.Database.EntityRepo.Entities.GroupCalibration", b =>
                {
                    b.Property<Guid>("GroupCailbrationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("groupCailbrationId");

                    b.Property<string>("AditionalInfo")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT")
                        .HasColumnName("aditionalInfo");

                    b.Property<Guid>("CameraId")
                        .HasColumnType("TEXT")
                        .HasColumnName("cameraId");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnName("date");

                    b.Property<Guid>("IncreaseId")
                        .HasColumnType("TEXT")
                        .HasColumnName("increaseId");

                    b.Property<Guid>("MicroscopeId")
                        .HasColumnType("TEXT")
                        .HasColumnName("microscopeId");

                    b.HasKey("GroupCailbrationId");

                    b.HasIndex("CameraId");

                    b.HasIndex("IncreaseId");

                    b.HasIndex("MicroscopeId");

                    b.ToTable("groupCalibration", (string)null);
                });

            modelBuilder.Entity("GotsThorlabs.Database.EntityRepo.Entities.Image", b =>
                {
                    b.Property<int>("IdImage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("idImage");

                    b.Property<double?>("GausianVal")
                        .HasColumnType("REAL")
                        .HasColumnName("gausianVal");

                    b.Property<int>("IdTour")
                        .HasColumnType("INTEGER")
                        .HasColumnName("idTour");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("path");

                    b.Property<int>("X")
                        .HasColumnType("INTEGER")
                        .HasColumnName("X");

                    b.Property<int>("Y")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Y");

                    b.Property<int>("Z")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Z");

                    b.HasKey("IdImage");

                    b.HasIndex("IdTour");

                    b.ToTable("image", (string)null);
                });

            modelBuilder.Entity("GotsThorlabs.Database.EntityRepo.Entities.Increase", b =>
                {
                    b.Property<Guid>("IncreaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("increaseId");

                    b.Property<string>("AditionalInfo")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT")
                        .HasColumnName("aditionalInfo");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<decimal>("Value")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("IncreaseId");

                    b.ToTable("increase", (string)null);
                });

            modelBuilder.Entity("GotsThorlabs.Database.EntityRepo.Entities.Microscope", b =>
                {
                    b.Property<Guid>("MicroscopeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("microscopeId");

                    b.Property<string>("AditionalInfo")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT")
                        .HasColumnName("aditionalInfo");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT")
                        .HasColumnName("brand");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Site")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT")
                        .HasColumnName("site");

                    b.HasKey("MicroscopeId");

                    b.ToTable("microscope", (string)null);
                });

            modelBuilder.Entity("GotsThorlabs.Database.EntityRepo.Entities.PicsCalibration", b =>
                {
                    b.Property<Guid>("PicsCalibrationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("picsCalibrationId");

                    b.Property<bool>("Acepted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("acepted");

                    b.Property<string>("AxeDirectionCalibration")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT")
                        .HasColumnName("axeDirectionCalibration");

                    b.Property<decimal>("Confidence")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT")
                        .HasColumnName("confidence");

                    b.Property<Guid>("GroupCailbrationId")
                        .HasColumnType("TEXT")
                        .HasColumnName("groupCailbrationId");

                    b.Property<string>("MeasureUnit")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT")
                        .HasColumnName("measureUnit");

                    b.Property<decimal>("MovementValue")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT")
                        .HasColumnName("movementValue");

                    b.Property<string>("Pic1")
                        .IsRequired()
                        .HasMaxLength(1200)
                        .HasColumnType("TEXT")
                        .HasColumnName("pic1");

                    b.Property<string>("Pic2")
                        .IsRequired()
                        .HasMaxLength(1200)
                        .HasColumnType("TEXT")
                        .HasColumnName("pic2");

                    b.Property<decimal>("dx")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT")
                        .HasColumnName("dx");

                    b.Property<decimal>("dy")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT")
                        .HasColumnName("dy");

                    b.HasKey("PicsCalibrationId");

                    b.HasIndex("GroupCailbrationId");

                    b.ToTable("picsCalibration", (string)null);
                });

            modelBuilder.Entity("GotsThorlabs.Database.EntityRepo.Entities.Tour", b =>
                {
                    b.Property<int>("IdTour")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("idTour");

                    b.Property<int>("Camera")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Camera");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnName("date");

                    b.Property<string>("EndStatus")
                        .HasColumnType("TEXT")
                        .HasColumnName("endStatus");

                    b.Property<string>("NameFolder")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nameFolder");

                    b.Property<int>("NumberX")
                        .HasColumnType("INTEGER")
                        .HasColumnName("NumberX");

                    b.Property<int>("NumberY")
                        .HasColumnType("INTEGER")
                        .HasColumnName("NumberY");

                    b.Property<int>("NumberZ")
                        .HasColumnType("INTEGER")
                        .HasColumnName("NumberZ");

                    b.HasKey("IdTour");

                    b.ToTable("tour", (string)null);
                });

            modelBuilder.Entity("GotsThorlabs.Database.EntityRepo.Entities.User", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("idUser");

                    b.Property<string>("EMail")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("eMail");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nickname");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("password");

                    b.HasKey("IdUser");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("GotsThorlabs.Database.EntityRepo.Entities.GroupCalibration", b =>
                {
                    b.HasOne("GotsThorlabs.Database.EntityRepo.Entities.Camera", "Camera")
                        .WithMany("GroupCalibrations")
                        .HasForeignKey("CameraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GotsThorlabs.Database.EntityRepo.Entities.Increase", "Increase")
                        .WithMany("GroupCalibrations")
                        .HasForeignKey("IncreaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GotsThorlabs.Database.EntityRepo.Entities.Microscope", "Microscope")
                        .WithMany("GroupCalibrations")
                        .HasForeignKey("MicroscopeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Camera");

                    b.Navigation("Increase");

                    b.Navigation("Microscope");
                });

            modelBuilder.Entity("GotsThorlabs.Database.EntityRepo.Entities.Image", b =>
                {
                    b.HasOne("GotsThorlabs.Database.EntityRepo.Entities.Tour", "Tour")
                        .WithMany("Images")
                        .HasForeignKey("IdTour")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("GotsThorlabs.Database.EntityRepo.Entities.PicsCalibration", b =>
                {
                    b.HasOne("GotsThorlabs.Database.EntityRepo.Entities.GroupCalibration", "GroupCalibration")
                        .WithMany("PicsCalibrations")
                        .HasForeignKey("GroupCailbrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GroupCalibration");
                });

            modelBuilder.Entity("GotsThorlabs.Database.EntityRepo.Entities.Camera", b =>
                {
                    b.Navigation("GroupCalibrations");
                });

            modelBuilder.Entity("GotsThorlabs.Database.EntityRepo.Entities.GroupCalibration", b =>
                {
                    b.Navigation("PicsCalibrations");
                });

            modelBuilder.Entity("GotsThorlabs.Database.EntityRepo.Entities.Increase", b =>
                {
                    b.Navigation("GroupCalibrations");
                });

            modelBuilder.Entity("GotsThorlabs.Database.EntityRepo.Entities.Microscope", b =>
                {
                    b.Navigation("GroupCalibrations");
                });

            modelBuilder.Entity("GotsThorlabs.Database.EntityRepo.Entities.Tour", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
