// <auto-generated />
using System;
using GotsThorlabs.Database.EntityRepo;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GotsThorlabs.Migrations
{
    [DbContext(typeof(ThorlabsDbContext))]
    partial class ThorlabsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.36");

            modelBuilder.Entity("GotsThorlabs.Database.EntityRepo.Entities.Camera", b =>
                {
                    b.Property<string>("CameraId")
                        .HasColumnType("TEXT")
                        .HasColumnName("cameraId");

                    b.Property<string>("DriverType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("driverType");

                    b.Property<string>("Features")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("features");

                    b.Property<string>("LocalIdentifier")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("localIdentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("SettingsJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("settingsJson");

                    b.HasKey("CameraId");

                    b.ToTable("camera", (string)null);
                });

            modelBuilder.Entity("GotsThorlabs.Database.EntityRepo.Entities.GroupCalibration", b =>
                {
                    b.Property<string>("GroupCailbrationId")
                        .HasColumnType("TEXT")
                        .HasColumnName("groupCailbrationId");

                    b.Property<string>("AditionalInfo")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("aditionalInfo");

                    b.Property<string>("CameraId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("cameraId");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("date");

                    b.Property<string>("IncreaseId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("increaseId");

                    b.Property<string>("MicroscopeId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("microscopeId");

                    b.HasKey("GroupCailbrationId");

                    b.HasIndex("CameraId");

                    b.HasIndex("IncreaseId");

                    b.HasIndex("MicroscopeId");

                    b.ToTable("groupCalibration", (string)null);
                });

            modelBuilder.Entity("GotsThorlabs.Database.EntityRepo.Entities.Image", b =>
                {
                    b.Property<long>("IdImage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("idImage");

                    b.Property<double?>("GausianVal")
                        .HasColumnType("REAL")
                        .HasColumnName("gausianVal");

                    b.Property<long>("IdTour")
                        .HasColumnType("INTEGER")
                        .HasColumnName("idTour");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("path");

                    b.Property<long>("X")
                        .HasColumnType("INTEGER")
                        .HasColumnName("X");

                    b.Property<long>("Y")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Y");

                    b.Property<long>("Z")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Z");

                    b.HasKey("IdImage");

                    b.HasIndex("IdTour");

                    b.ToTable("image", (string)null);
                });

            modelBuilder.Entity("GotsThorlabs.Database.EntityRepo.Entities.Increase", b =>
                {
                    b.Property<string>("IncreaseId")
                        .HasColumnType("TEXT")
                        .HasColumnName("increaseId");

                    b.Property<string>("AditionalInfo")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("aditionalInfo");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("IncreaseId");

                    b.ToTable("increase", (string)null);
                });

            modelBuilder.Entity("GotsThorlabs.Database.EntityRepo.Entities.Microscope", b =>
                {
                    b.Property<string>("MicroscopeId")
                        .HasColumnType("TEXT")
                        .HasColumnName("microscopeId");

                    b.Property<string>("AditionalInfo")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("aditionalInfo");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("brand");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Site")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("site");

                    b.HasKey("MicroscopeId");

                    b.ToTable("microscope", (string)null);
                });

            modelBuilder.Entity("GotsThorlabs.Database.EntityRepo.Entities.PicsCalibration", b =>
                {
                    b.Property<string>("PicsCalibrationId")
                        .HasColumnType("TEXT")
                        .HasColumnName("picsCalibrationId");

                    b.Property<long>("Acepted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("acepted");

                    b.Property<string>("AxeDirectionCalibration")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("axeDirectionCalibration");

                    b.Property<string>("AxisMovementName")
                        .HasColumnType("TEXT")
                        .HasColumnName("axisMovementName");

                    b.Property<string>("Confidence")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("confidence");

                    b.Property<string>("Dx")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("dx");

                    b.Property<string>("Dy")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("dy");

                    b.Property<string>("GroupCailbrationId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("groupCailbrationId");

                    b.Property<string>("MeasureUnit")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("measureUnit");

                    b.Property<string>("MovementValue")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("movementValue");

                    b.Property<long?>("NumberOfSteps")
                        .HasColumnType("INTEGER")
                        .HasColumnName("numberOfSteps");

                    b.Property<string>("Pic1")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("pic1");

                    b.Property<string>("Pic2")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("pic2");

                    b.HasKey("PicsCalibrationId");

                    b.HasIndex("GroupCailbrationId");

                    b.ToTable("picsCalibration", (string)null);
                });

            modelBuilder.Entity("GotsThorlabs.Database.EntityRepo.Entities.Tour", b =>
                {
                    b.Property<long>("IdTour")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("idTour");

                    b.Property<long>("Camera")
                        .HasColumnType("INTEGER")
                        .HasColumnName("Camera");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("date");

                    b.Property<string>("EndStatus")
                        .HasColumnType("TEXT")
                        .HasColumnName("endStatus");

                    b.Property<string>("NameFolder")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nameFolder");

                    b.Property<long>("NumberX")
                        .HasColumnType("INTEGER")
                        .HasColumnName("NumberX");

                    b.Property<long>("NumberY")
                        .HasColumnType("INTEGER")
                        .HasColumnName("NumberY");

                    b.Property<long>("NumberZ")
                        .HasColumnType("INTEGER")
                        .HasColumnName("NumberZ");

                    b.Property<string>("PicsCalibrationId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("picsCalibrationId");

                    b.HasKey("IdTour");

                    b.HasIndex("PicsCalibrationId");

                    b.ToTable("tour", (string)null);
                });

            modelBuilder.Entity("GotsThorlabs.Database.EntityRepo.Entities.User", b =>
                {
                    b.Property<long>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("idUser");

                    b.Property<string>("EMail")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("eMail");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nickname");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("password");

                    b.HasKey("IdUser");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("GotsThorlabs.Database.EntityRepo.Entities.GroupCalibration", b =>
                {
                    b.HasOne("GotsThorlabs.Database.EntityRepo.Entities.Camera", "Camera")
                        .WithMany("GroupCalibrations")
                        .HasForeignKey("CameraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GotsThorlabs.Database.EntityRepo.Entities.Increase", "Increase")
                        .WithMany("GroupCalibrations")
                        .HasForeignKey("IncreaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GotsThorlabs.Database.EntityRepo.Entities.Microscope", "Microscope")
                        .WithMany("GroupCalibrations")
                        .HasForeignKey("MicroscopeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Camera");

                    b.Navigation("Increase");

                    b.Navigation("Microscope");
                });

            modelBuilder.Entity("GotsThorlabs.Database.EntityRepo.Entities.Image", b =>
                {
                    b.HasOne("GotsThorlabs.Database.EntityRepo.Entities.Tour", "Tour")
                        .WithMany("Images")
                        .HasForeignKey("IdTour")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("GotsThorlabs.Database.EntityRepo.Entities.PicsCalibration", b =>
                {
                    b.HasOne("GotsThorlabs.Database.EntityRepo.Entities.GroupCalibration", "GroupCalibration")
                        .WithMany("PicsCalibrations")
                        .HasForeignKey("GroupCailbrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GroupCalibration");
                });

            modelBuilder.Entity("GotsThorlabs.Database.EntityRepo.Entities.Tour", b =>
                {
                    b.HasOne("GotsThorlabs.Database.EntityRepo.Entities.PicsCalibration", "PicsCalibration")
                        .WithMany("Tours")
                        .HasForeignKey("PicsCalibrationId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .IsRequired();

                    b.Navigation("PicsCalibration");
                });

            modelBuilder.Entity("GotsThorlabs.Database.EntityRepo.Entities.Camera", b =>
                {
                    b.Navigation("GroupCalibrations");
                });

            modelBuilder.Entity("GotsThorlabs.Database.EntityRepo.Entities.GroupCalibration", b =>
                {
                    b.Navigation("PicsCalibrations");
                });

            modelBuilder.Entity("GotsThorlabs.Database.EntityRepo.Entities.Increase", b =>
                {
                    b.Navigation("GroupCalibrations");
                });

            modelBuilder.Entity("GotsThorlabs.Database.EntityRepo.Entities.Microscope", b =>
                {
                    b.Navigation("GroupCalibrations");
                });

            modelBuilder.Entity("GotsThorlabs.Database.EntityRepo.Entities.Tour", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("GotsThorlabs.Database.EntityRepo.Entities.PicsCalibration", b =>
                {
                    b.Navigation("Tours");
                });
#pragma warning restore 612, 618
        }
    }
}
